### PR TITLE
package.json: specify the files to include in the npm package

### PR DESCRIPTION
**Pull request by XhmikosR**
For some reason, currently package.json lacks a version property BTW.

This works but still includes the `lib/**/README.md` files which are a lot.

I don't get why this happens, so, If you have any ideas how to exclude those too, that would be the best. :)

You can try with `npm pack --dry` to see the included files.

I'm using npm 9.5.0, maybe it's a bug with this version.

### CODE REVIEW

**Comment by elirasza** [comment]
The version property is dynamically added on tag, see the GitHub actions script : https://github.com/elirasza/stylelint-stylistic/blob/main/.github/scripts/deploy.sh#L4. The published result has it : https://www.npmjs.com/package/stylelint-stylistic?activeTab=code.

Regarding each rule README.md however, they should be explicitely excluded with a rule like `"!lib/**/README.md"`. IIRC all README.md and LICENSE.md are always added regardless of configuration : https://docs.npmjs.com/cli/v9/configuring-npm/package-json#files. I believe they should be deleted just before publishing ?

**Comment by XhmikosR** [comment]
I'm pretty sure only the root README.md was included in the past, maybe it's an npm regression or change in behavior.

A workaround would be to indeed delete the README.md files except for the root README.md on CI before publishing.

**Comment by elirasza** [comment]
After changing .npmignore to the files array in package.json, it seems that the subfolders README.md are not ignored ! I will merge your changes in the demo branch, as I am working in a related package change.

**Comment by XhmikosR** [comment]
> After changing .npmignore to the files array in package.json, it seems that the subfolders README.md are not ignored ! I will merge your changes in the demo branch, as I am working in a related package change.

Nice :)

BTW, did you really mean to close the PR?

**Comment by elirasza** [comment]
Huu, I may have messed up the merging, it's the first time I do it on GitHub as I always used Gitlab at work ! Your changes have been merged in https://github.com/elirasza/stylelint-stylistic/commit/37e0fcf29e9d327558e0018c230bd84a2b8cee84 :)

**Comment by elirasza** [comment]
As it is already merged

**Comment by XhmikosR** [comment]
@elirasza FYI https://github.com/npm/cli/issues/6341

So, it seems like a bug with npm 9.x. If one uses Node.js 16.x for publishing or directly npm 8.x, the issue is not present.

**Comment by elirasza** [comment]
Thank you for the issue on NPM ! It might well be a bug on their side. We should be able to exclude these files without downgrading npm.

**Pull request closed without merging**
